model_path: /mnt/shared/models/sam3-base
test_json_path: ./data_split/new_test_data.json
img_path: /mnt/shared/AGD20K/

image_size: 896

use_lora: False
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05

load_model_path: ./checkpoints/affordance_sam3_nolora_nobinmask_2
output_image_path: ./test_outputs/affordance_sam3_nolora_nobinmask_2

batch_size: 1
